CREATE DATABASE SIRKET
USE SIRKET
CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
SAA NVARCHAR (100),
VEZIFEID INT REFERENCES VEZIFE(ID),
MAAS INT)

SELECT* FROM ISCI

INSERT INTO ISCI VALUES('FidanMammadova',2,450)

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100)
)

INSERT INTO VEZIFE VALUES('satici')
SELECT*FROM VEZIFE


CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100))

INSERT INTO FILIAL VALUES('BAKU')

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100),
ISCIID INT REFERENCES ISCI(ID),
SATISQIYMETI INT)

ALTER TABLE MEHSUL
ADD  ALISQIYMETI INT


select * from mehsul
INSERT INTO MEHSUL VALUES('DRESS',1,60,30)

CREATE TABLE SATIS(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
SATISTARIXI DATE DEFAULT GETDATE())

INSERT INTO SATIS VALUES(5,1,1,'2021.02.15')
SELECT *FROM SATIS

--SORGU1
SELECT ISCI.SAA, MEHSUL.AD, FILIAL.AD, MEHSUL.ALISQIYMETI, MEHSUL.SATISQIYMETI FROM SATIS
JOIN FILIAL AS FILIAL
ON SATIS.FILIALID=FILIAL.ID
JOIN ISCI AS ISCI
ON ISCIID=ISCI.ID
JOIN MEHSUL AS MEHSUL
ON MEHSULID=MEHSUL.ID

--SORGU2
SELECT SUM(SATISQIYMETI) AS 'BUTUN SATIS'
FROM SATIS
JOIN MEHSUL
ON MEHSUL.ID=SATIS.MEHSULID

--SORGU3
SELECT SUM(SATISQIYMETI) FROM MEHSUL JOIN SATIS
ON SATIS.MEHSULID=MEHSUL.ID
WHERE MONTH(SATISTARIXI)=MONTH(GETDATE())


