CREATE DATABASE STUDENT 
USE STUDENT
CREATE TABLE STUDENTS(
Id int,
[Name] nvarchar(50),
Surname nvarchar(50),
Age int,
Grade int)
SELECT [Name]+' '+Surname AS FULLNAME FROM STUDENTS
INSERT INTO STUDENTS VALUES(1,'Fidan','Mammadova',19,81)
INSERT INTO STUDENTS VALUES(2,'Murad','Abdullazade',18,99)
SELECT * FROM STUDENTS
SELECT * FROM STUDENTS WHERE Grade<(SELECT AVG(Grade) FROM STUDENTS)
SELECT * FROM STUDENTS WHERE Grade>(SELECT AVG(Grade) FROM STUDENTS)
SELECT * FROM STUDENTS WHERE Age=(SELECT MIN(Age) FROM STUDENTS)
SELECT * FROM STUDENTS WHERE Age=(SELECT MAX(Age) FROM STUDENTS)



